# Permalinks
permalink:        /:title

# Setup
title:            Government Status
tagline:          Is the government down today?
description:      Tracking the status of governments around the world
url:              www.governmentstat.us
baseurl:          /governmentstat.us

# Pagination number
paginate:         10

# category page
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
